name: BitGrid
version: '1.0-release'
main: net.bitgrid.Bitgrid
api-version: '1.21'
authors: [ Dev-Wonjoon ]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.9.0
  - com.zaxxer:HikariCP:5.1.0
  - com.mysql:mysql-connector-j:9.0.0
  - org.jetbrains.exposed:exposed-core:0.56.0
  - org.jetbrains.exposed:exposed-dao:0.56.0
  - org.jetbrains.exposed:exposed-jdbc:0.56.0

commands:
  bitgrid:
    description: BitGrid Storage Management
    usage: /bitgrid <give|invite|kick|members|leave>

permissions:
  bitgrid.use:
    description: Storage Core use
    default: true
  bitgrid.craft:
    description: Storage Core crafting
    default: true
  bitgrid.admin:
    description: Storage Core admin
    default: op

libraries:
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.22.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.22.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3
  - org.jetbrains.exposed:exposed-core:0.56.0
  - org.jetbrains.exposed:exposed-dao:0.56.0
  - org.jetbrains.exposed:exposed-jdbc:0.56.0
  - org.xerial:sqlite-jdbc:3.47.1.0
  - com.zaxxer:HikariCP:6.2.1