database:
  type: sqlite
  host: localhost
  port: 3306
  name: net.bitgrid
  username: root
  password: ""

storage-core:
    crafting:
      enabled: true
      recipe:
        row1: ["DIAMOND", "ENDER_PEARL", "DIAMOND"]
        row2: ["ENDER_PEARL", "BARREL", "ENDER_PEARL"]
        row3: ["DIAMOND", "ENDER_PEARL", "DIAMOND"]

    upgrades:
      stack:
        max-level: 6
        price-type: "VAULT" # EXP or VAULT
        costs: [10, 20, 30, 40, 50, 60]
        limits: [256, 1024, 4096, 16384, 65536, 131072, 262144]
      page:
        max-level: 6
        price-type: "VAULT" # EXP or VAULT
        costs: [10, 20, 30, 40, 50, 60]
        limits: [3, 5, 7, 9, 11, 13, 15]